Added polygonize method
rgeo/rgeo pull request #222
Opened 2020-08-23 22:50 UTC by tyfoan

### Summary

Added polygonize method of linestring and multilinestring

Thanks for contributing!

2020-10-08 13:19 UTC, keithdoggett commented
Thank you for submitting this and #221! I'm currently going through the issue backlog but will be able to review this and hopefully merge within the next few weeks.

2020-10-21 16:21 UTC, keithdoggett commented on test/geos_capi/multi_line_string_test.rb
> +    )")
While this properly demonstrates the behavior, the geometry is a little complex and the coordinates are cumbersome due to their precision. I came up with this example that I think would be easier to debug/expand upon but still tests the method properly.

```rb
polygon1_wkt = "POLYGON ((0 0, 0 1, 1 1, 1 0, 0 0))"
polygon2_wkt = "POLYGON ((1 0, 1 1, 2 1, 2 0, 1 0))"

expected = @factory.parse_wkt("GEOMETRYCOLLECTION(#{polygon1_wkt}, #{polygon2_wkt})")

multi_line_string_wkt = "MULTILINESTRING( (1 1, 0 1, 0 0, 1 0), (1 -1, 1 0, 1 1, 1 2), (1 1, 2 1, 2 0, 1 0) )"
multi_line_string = @factory.parse(multi_line_string_wkt)
```

2020-10-21 16:26 UTC, keithdoggett commented
In addition to the above change, adding a test that confirms proper behavior on a failure should be included. Per the geos comments any of these should suffice:

```c
/*
 * The Polygonizer reports the follow kinds of errors:
 *
 * - Dangles - edges which have one or both ends which are
 *   not incident on another edge endpoint
 * - Cut Edges - edges which are connected at both ends but
 *   which do not form part of a polygon
 * - Invalid Ring Lines - edges which form rings which are invalid
 *   (e.g. the component lines contain a self-intersection)
*/
```

Also since this includes the same changes as #221, the comment from that could just be rolled into the changes here.

2020-12-11 20:27 UTC, keithdoggett requested changes

2020-12-11 20:27 UTC, keithdoggett commented on ext/geos_c_impl/geometry.c
> +
`GeosOffsetCurve_r` only works on `linestrings` per the comments in `geos_c.h`

2020-12-11 20:27 UTC, keithdoggett commented on ext/geos_c_impl/geometry_collection.c
> +static VALUE method_line_string_polygonize(VALUE self)
Please change this to `method_multi_line_string_polygonize`

2020-12-11 20:27 UTC, keithdoggett commented on test/geos_capi/line_string_test.rb
> +    ]
Can you use simpler coordinates for this test?

2020-12-11 20:27 UTC, keithdoggett commented on test/geos_capi/line_string_test.rb
> +    ]
Can you use a simpler set of coordinates?

2020-12-11 20:29 UTC, keithdoggett commented
I'd also like it if you try to do what I mentioned in this [comment](https://github.com/rgeo/rgeo/pull/222#issuecomment-713698022) and add some edge cases to the tests so we understand the impact on the library.

Additionally, please confirm that this PR includes all of the same changes as #211. If that is the case, then we should close that PR and just merge this.

2022-02-08 14:30 UTC, keithdoggett reviewed
Thanks @tyfoan these tests look a lot better! Just change that method name and then it's good for me.

2022-02-08 14:30 UTC, keithdoggett commented on test/geos_capi/line_string_test.rb
> +  def do_test_polygonize(expected_wkt, input_wkt)
minor tweak, but can we change this to `assert_polygonize_equal`

2022-02-08 14:30 UTC, keithdoggett commented on test/geos_capi/multi_line_string_test.rb
> +  def do_test_polygonize(expected_wkt, input_wkt)
minor tweak, but can we change this to `assert_polygonize_equal`

2022-02-09 12:01 UTC, BuonOmo reviewed
Hey, thanks for the contribution!

@keithdoggett I definitely agree that some guidance may help (maybe in a CONTRIBUTING.md to follow github’s guidelines)

On the PRs content: I think we are missing some things.

On error, the polygonize geos method would return null, don’t we want to raise instead ? ([related doc](https://libgeos.org/doxygen/geos__c_8h.html#a9d98e448d3b846d591c726d1c0000d25)).

Also the method is undocumented, I think that is an issue and we should care to document it, either by linking to GEOS documentation directly if we do not change the interface, or adding our own doc.

Documenting C methods can be done thanks to the rdoc C parser https://ruby.github.io/rdoc/RDoc/Parser/C.html. I think we need to add documentation upfront even though it only works in v3-dev branch (yet) to make sure we don’t have too much documentation work afterwards.

2022-02-16 20:24 UTC, keithdoggett commented
@tyfoan could you just add a check if the result of `rgeo_wrap_geos_geometry` is `Qnil` and if it is raising an error with `rb_raise`? I think that would solve the issue for now and maybe eventually we can move that logic into the wrapping function. @BuonOmo

2022-02-25 22:27 UTC, keithdoggett commented
@tyfoan I agree since it may affect other methods and tests. So I guess the only thing left to do is document the function with a comment like @BuonOmo pointed out.

2022-03-11 18:01 UTC, BuonOmo commented
Hey @tyfoan,

Sorry for both the delay and lack of information in my previous message. I'll try to be more thorough here, and note that I can help further if needed.

## On returning `nil` vs raising

Indeed, it would be a tall task to ask from you to change `rgeo_wrap_geos_geometry`, and even though this is something we could think about, here it is really not the case. 

Since GEOS already gives us the information that the geometry is invalid by returning `null` before we have to cast to a rgeo value, that is already a good place to raise an error. Hence you'd be really focusing on a change that is really local to that PR.

Moreover, per GEOS documentation, the [`GEOSPolygonize_r`](https://libgeos.org/doxygen/geos__c_8h.html#a9d98e448d3b846d591c726d1c0000d25) method does in fact way more than what we check here. Among everything it does, there is:

> The Polygonizer reports the following kinds of errors:
>
> - Dangles - edges which have one or both ends which are not incident on another edge endpoint
> - Cut Edges - edges which are connected at both ends but which do not form part of a polygon
> - Invalid Ring Lines - edges which form rings which are invalid (e.g. the component lines contain a self-intersection)
>
> Errors are reported to output parameters "cuts", "dangles" and "invalid" (if not-null). Formed polygons are returned as a collection. NULL is returned on exception. All returned geometries must be destroyed by caller.

However, I've tried adding notice handlers to the PR and check for those, and I've seen nothing. Hence I think the tests only cover the successful part of `#polygonize`, not the failing on unfortunetaly... Here's a patch to add those handlers locally:

```diff
diff --git a/ext/geos_c_impl/factory.c b/ext/geos_c_impl/factory.c
index 8dc2025..cd73786 100644
--- a/ext/geos_c_impl/factory.c
+++ b/ext/geos_c_impl/factory.c
@@ -29,10 +29,25 @@ RGEO_BEGIN_C
 // NOP message handler. GEOS requires that a message handler be set
 // for every context handle.
 
-static void message_handler(const char* fmt, ...)
+static void notice_handler(const char* fmt, ...)
 {
+  va_list args;
+  va_start(args, fmt);
+  fprintf(stderr, "GEOS Notice -- ");
+  vfprintf(stderr, fmt, args);
+  fprintf(stderr, "\n");
+  va_end(args);
 }
 
+static void error_handler(const char* fmt, ...)
+{
+  va_list args;
+  va_start(args, fmt);
+  fprintf(stderr, "GEOS Error -- ");
+  vfprintf(stderr, fmt, args);
+  fprintf(stderr, "\n");
+  va_end(args);
+}
 
 // Destroy function for factory data. We destroy any serialization
 // objects that have been created for the factory, and then destroy
@@ -459,7 +474,7 @@ static VALUE cmethod_factory_create(VALUE klass, VALUE flags, VALUE srid, VALUE
   result = Qnil;
   data = ALLOC(RGeo_FactoryData);
   if (data) {
-    context = initGEOS_r(message_handler, message_handler);
+    context = initGEOS_r(notice_handler, error_handler);
     if (context) {
       data->geos_context = context;
       data->flags = NUM2INT(flags);

```

And I also think we should raise when an error message happens. Luckily, we're already working on that in the v3-dev branch (https://github.com/rgeo/rgeo/commit/a2f678da953024fd8cf1079954de7d6504dadbbe), so it is _kind of ok_ to keep it that way if we are sure we at least have tests covering those error messages.

SIDE: @keithdoggett we're more and more having conflicts between our v3-dev development and community's input, since we'd love more of that input I think we should release soon a `3.0.0-pre` version, WDYT?

## On documentation

I really have to insist on that since one day, someone will have to do it anyway hence we should start documenting new methods as they arrive. However, there are no examples available yet so I'll give it a try:

```diff
diff --git a/.yardopts b/.yardopts
index 133ac4f..bdf164f 100644
--- a/.yardopts
+++ b/.yardopts
@@ -1,5 +1,6 @@
 --markup rdoc
 --output-dir ./yardoc
 lib/**/*.rb
+ext/**/*.{c,h}
 -
 doc/*.md
diff --git a/Rakefile b/Rakefile
index ec5005f..091ced6 100644
--- a/Rakefile
+++ b/Rakefile
@@ -3,6 +3,8 @@
 require "rake/testtask"
 require "rake/extensiontask"
 require "bundler/gem_tasks"
+require "yard"
+
 
 # Build tasks
 
@@ -30,5 +32,12 @@ Rake::TestTask.new(:test) do |t|
   t.test_files = FileList["test/**/*_test.rb"]
 end
 
+YARD::Rake::YardocTask.new do |t|
+  # Runs a server to appreciate doc after having it running
+  t.after = proc do
+    exec "ruby", "-run", "-e", "httpd", File.join(__dir__, "yardoc")
+  end
+end
+
 task test: :compile
 task default: [:clean, :test]
diff --git a/ext/geos_c_impl/geometry_collection.c b/ext/geos_c_impl/geometry_collection.c
index be20de4..1358e4f 100644
--- a/ext/geos_c_impl/geometry_collection.c
+++ b/ext/geos_c_impl/geometry_collection.c
@@ -408,35 +408,6 @@ static VALUE method_multi_line_string_coordinates(VALUE self)
   return result;
 }
 
-
-static VALUE method_multi_line_string_polygonize(VALUE self)
-{
-  VALUE result;
-  RGeo_GeometryData* self_data;
-  const GEOSGeometry* self_geom;
-  GEOSGeometry* geos_polygon_collection;
-  VALUE factory;
-
-  result = Qnil;
-
-  self_data = RGEO_GEOMETRY_DATA_PTR(self);
-  self_geom = self_data->geom;
-
-  if (self_geom) {
-    factory = self_data->factory;
-    geos_polygon_collection = GEOSPolygonize_r(self_data->geos_context, &self_geom, 1);
-
-    result = rgeo_wrap_geos_geometry(
-        factory,
-        geos_polygon_collection,
-        Qnil
-      );
-  }
-
-  return result;
-}
-
-
 static VALUE method_multi_line_string_length(VALUE self)
 {
   VALUE result;
@@ -650,7 +621,7 @@ void rgeo_init_geos_geometry_collection()
   rb_define_method(geos_multi_line_string_methods, "closed?", method_multi_line_string_is_closed, 0);
   rb_define_method(geos_multi_line_string_methods, "hash", method_multi_line_string_hash, 0);
   rb_define_method(geos_multi_line_string_methods, "coordinates", method_multi_line_string_coordinates, 0);
-  rb_define_method(geos_multi_line_string_methods, "polygonize", method_multi_line_string_polygonize, 0);
+  rb_define_method(geos_multi_line_string_methods, "polygonize", method_line_string_polygonize, 0);
 
   // Methods for MultiPolygonImpl
   geos_multi_polygon_methods = rb_define_module_under(rgeo_geos_module, "CAPIMultiPolygonMethods");
diff --git a/ext/geos_c_impl/line_string.c b/ext/geos_c_impl/line_string.c
index ab6294f..61f5464 100644
--- a/ext/geos_c_impl/line_string.c
+++ b/ext/geos_c_impl/line_string.c
@@ -125,8 +125,20 @@ static VALUE method_line_string_coordinates(VALUE self)
   return result;
 }
 
-
-static VALUE method_line_string_polygonize(VALUE self)
+/**
+ * call-seq:
+ *   some.polygonize -> RGeo::Feature::GeometryCollection
+ *
+ * Polygonizes a set of line strings which contain linework that represents
+ * the edges of a planar graph.
+ *
+ * The edges must be correctly noded; that is, they must only meet at
+ * their endpoints. Polygonization will accept incorrectly noded input
+ * but will not form polygons from non-noded edges, and TODO: change this according to what we are going to do with the method.
+ *
+ * @see https://libgeos.org/doxygen/geos__c_8h.html#a9d98e448d3b846d591c726d1c0000d25 GEOSPolygonize
+ */
+VALUE method_line_string_polygonize(VALUE self)
 {
   VALUE result;
   RGeo_GeometryData* self_data;
diff --git a/ext/geos_c_impl/line_string.h b/ext/geos_c_impl/line_string.h
index 7cb0799..721f19a 100644
--- a/ext/geos_c_impl/line_string.h
+++ b/ext/geos_c_impl/line_string.h
@@ -18,6 +18,9 @@ RGEO_BEGIN_C
 */
 void rgeo_init_geos_line_string();
 
+// This method is also used by multi_line_strings.
+VALUE method_line_string_polygonize(VALUE);
+
 /*
   Determines whether the given GEOS line string is closed.
   Returns Qtrue if true, Qfalse if false, or Qnil on an error.
diff --git a/rgeo.gemspec b/rgeo.gemspec
index be39127..c615c8c 100644
--- a/rgeo.gemspec
+++ b/rgeo.gemspec
@@ -28,4 +28,5 @@ Gem::Specification.new do |spec|
   spec.add_development_dependency "rake", "~> 13.0"
   spec.add_developmen [...]

2022-07-07 08:04 UTC, BuonOmo commented
Closed by #313

2022-07-07 15:38 UTC, closed without merging